# Generated by Django 2.0.3 on 2018-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0002_auto_20180503_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='imagesub',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
