# Generated by Django 2.0.3 on 2018-05-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0003_member_imagesub'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='imagesub',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
