# Generated by Django 2.0.3 on 2018-05-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180503_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='imagesub',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
