# Generated by Django 2.0.3 on 2018-03-26 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('url', models.URLField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('adv', models.IntegerField(default=0)),
                ('door', models.IntegerField(default=0)),
                ('artists', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
