# Generated by Django 2.0.3 on 2018-05-05 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_livecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livecontact',
            name='ticket',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
