# Generated by Django 2.0.3 on 2018-05-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
