# Generated by Django 2.0.3 on 2018-03-31 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('album', 'album'), ('single', 'single'), ('video', 'video'), ('book', 'book'), ('download', 'download')], max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('MPN', models.CharField(max_length=100, null=True)),
                ('release', models.DateField(null=True)),
                ('status', models.CharField(default='発売中', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='disc/')),
                ('songs', models.TextField(null=True)),
                ('catchcopy', models.CharField(max_length=200, null=True)),
                ('comment', models.TextField(null=True)),
                ('information', models.TextField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
