# Generated by Django 2.0.3 on 2018-05-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0002_auto_20180406_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='status',
            field=models.CharField(blank=True, default='発売中', max_length=200, null=True),
        ),
    ]
