# Generated by Django 2.0.3 on 2018-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0003_auto_20180503_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='imagesub',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
