# Generated by Django 2.0.3 on 2018-04-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='URL',
        ),
    ]
